-- V001 — QuickCart core operational schema (kit/04_DATA_MODEL_AND_EVENTS.md §2)
-- Money: NUMERIC(12,2). Timestamps: TIMESTAMPTZ (UTC). Statuses: CHECK-constraint enums.

CREATE TABLE stores (
    store_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code        TEXT NOT NULL UNIQUE,
    name              TEXT NOT NULL,
    city              TEXT NOT NULL,
    latitude          NUMERIC(9,6) NOT NULL,
    longitude         NUMERIC(9,6) NOT NULL,
    service_radius_km NUMERIC(5,2)  NOT NULL DEFAULT 5.0 CHECK (service_radius_km > 0),
    opened_at         TIMESTAMPTZ NOT NULL,
    is_active         BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE customers (
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code TEXT NOT NULL UNIQUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_active     BOOLEAN   NOT NULL DEFAULT TRUE
);

CREATE TABLE customer_addresses (
    address_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(customer_id),
    city        TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    latitude    NUMERIC(9,6) NOT NULL,
    longitude   NUMERIC(9,6) NOT NULL,
    is_default  BOOLEAN   NOT NULL DEFAULT FALSE,
    valid_from  TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to    TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE products (
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    category    TEXT NOT NULL,
    subcategory TEXT NOT NULL,
    brand       TEXT NOT NULL,
    unit_size   NUMERIC(10,3) NOT NULL CHECK (unit_size > 0),
    unit_name   TEXT NOT NULL,
    is_active   BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE product_prices (
    product_price_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT NOT NULL REFERENCES products(product_id),
    store_id         BIGINT REFERENCES stores(store_id), -- NULL = global price
    mrp              NUMERIC(12,2) NOT NULL CHECK (mrp >= 0),
    selling_price    NUMERIC(12,2) NOT NULL CHECK (selling_price >= 0),
    valid_from       TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to         TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (selling_price <= mrp)
);

CREATE TABLE inventory (
    store_id      BIGINT  NOT NULL REFERENCES stores(store_id),
    product_id    BIGINT  NOT NULL REFERENCES products(product_id),
    on_hand_qty   INTEGER NOT NULL DEFAULT 0 CHECK (on_hand_qty >= 0),
    reserved_qty  INTEGER NOT NULL DEFAULT 0 CHECK (reserved_qty >= 0),
    reorder_point INTEGER NOT NULL DEFAULT 0 CHECK (reorder_point >= 0),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (store_id, product_id)
);

CREATE TABLE inventory_movements (
    movement_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id       BIGINT NOT NULL REFERENCES stores(store_id),
    product_id     BIGINT NOT NULL REFERENCES products(product_id),
    movement_type  TEXT NOT NULL CHECK (movement_type IN
        ('RECEIPT','ORDER_RESERVE','ORDER_RELEASE','SALE',
         'MANUAL_ADJUSTMENT','TRANSFER_IN','TRANSFER_OUT','DAMAGE')),
    quantity_delta INTEGER NOT NULL CHECK (quantity_delta <> 0),
    reference_type TEXT,
    reference_id   TEXT,
    occurred_at    TIMESTAMPTZ NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE riders (
    rider_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    home_store_id BIGINT  NOT NULL REFERENCES stores(store_id),
    status        TEXT    NOT NULL DEFAULT 'OFFLINE'
        CHECK (status IN ('AVAILABLE','BUSY','OFFLINE')),
    shift_start   TIME    NOT NULL,
    shift_end     TIME    NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE promotions (
    promotion_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    promotion_type  TEXT NOT NULL CHECK (promotion_type IN ('PERCENT_OFF','FLAT_OFF','FREE_DELIVERY')),
    value           NUMERIC(12,2) NOT NULL CHECK (value >= 0),
    starts_at       TIMESTAMPTZ NOT NULL,
    ends_at         TIMESTAMPTZ NOT NULL,
    min_order_value NUMERIC(12,2),
    max_discount    NUMERIC(12,2),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (ends_at > starts_at)
);

CREATE TABLE orders (
    order_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT NOT NULL REFERENCES customers(customer_id),
    store_id       BIGINT NOT NULL REFERENCES stores(store_id),
    address_id     BIGINT REFERENCES customer_addresses(address_id),
    promotion_id   BIGINT REFERENCES promotions(promotion_id),
    status         TEXT NOT NULL DEFAULT 'PLACED' CHECK (status IN
        ('CREATED','PLACED','PAYMENT_PENDING','PAID','ACCEPTED','PICKING',
         'PACKED','RIDER_ASSIGNED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','REFUNDED')),
    subtotal       NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
    item_discount  NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (item_discount >= 0),
    promo_discount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (promo_discount >= 0),
    delivery_fee   NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
    tax_amount     NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    total_amount   NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
    currency       CHAR(3) NOT NULL DEFAULT 'INR',
    placed_at      TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT NOT NULL REFERENCES orders(order_id),
    product_id    BIGINT NOT NULL REFERENCES products(product_id),
    quantity      INTEGER NOT NULL CHECK (quantity > 0),
    unit_price    NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    line_discount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (line_discount >= 0),
    line_total    NUMERIC(12,2) NOT NULL CHECK (line_total >= 0),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payments (
    payment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL REFERENCES orders(order_id),
    payment_method TEXT NOT NULL CHECK (payment_method IN ('UPI','CARD','COD','WALLET','NETBANKING')),
    status         TEXT NOT NULL CHECK (status IN ('INITIATED','AUTHORIZED','CAPTURED','FAILED','REFUNDED')),
    amount         NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    currency       CHAR(3) NOT NULL DEFAULT 'INR',
    attempt_number INTEGER NOT NULL DEFAULT 1 CHECK (attempt_number >= 1),
    failure_code   TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE deliveries (
    delivery_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              BIGINT NOT NULL UNIQUE REFERENCES orders(order_id),
    rider_id              BIGINT REFERENCES riders(rider_id),
    promised_by           TIMESTAMPTZ NOT NULL,
    assigned_at           TIMESTAMPTZ,
    picked_up_at          TIMESTAMPTZ,
    delivered_at          TIMESTAMPTZ,
    cancelled_at          TIMESTAMPTZ,
    estimated_distance_km NUMERIC(6,2) NOT NULL CHECK (estimated_distance_km > 0),
    status                TEXT NOT NULL CHECK (status IN ('PENDING','ASSIGNED','PICKED_UP','DELIVERED','CANCELLED')),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE support_tickets (
    ticket_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT REFERENCES customers(customer_id),
    order_id     BIGINT REFERENCES orders(order_id),
    category     TEXT NOT NULL,
    priority     TEXT NOT NULL DEFAULT 'LOW' CHECK (priority IN ('LOW','MEDIUM','HIGH','URGENT')),
    status       TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
    subject      TEXT NOT NULL,
    body         TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
