-- V004 — Human-approved action proposals + audit trail (kit/03 §14.2–14.5).
-- The proposals table is the ONLY path through which the platform mutates the
-- operational DB outside the simulator/CDC: an agent or analyst recommends,
-- a human approves, a deterministic executor applies. Every status transition
-- lands in proposal_audit with a correlation id.

CREATE TABLE proposals (
    proposal_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_type     TEXT NOT NULL CHECK (proposal_type IN ('RESTOCK','INCIDENT','OPS_NOTIFICATION')),
    entity_scope      JSONB NOT NULL,
    recommended_action TEXT NOT NULL,
    reason            TEXT NOT NULL,
    evidence          JSONB NOT NULL DEFAULT '[]',
    source_request_id TEXT,
    validation_status TEXT NOT NULL DEFAULT 'PENDING',
    status            TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING','APPROVED','REJECTED','EXECUTED','FAILED')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_at       TIMESTAMPTZ,
    executed_at       TIMESTAMPTZ,
    approved_by       TEXT
);

CREATE TABLE proposal_audit (
    audit_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id    BIGINT NOT NULL REFERENCES proposals(proposal_id),
    from_status    TEXT,
    to_status      TEXT NOT NULL,
    actor          TEXT NOT NULL,
    detail         TEXT,
    correlation_id TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Duplicate-open-proposal lookups (validation rule: one open proposal per
-- store+product restock scope).
CREATE INDEX idx_proposals_status ON proposals (status);
CREATE INDEX idx_proposal_audit_proposal ON proposal_audit (proposal_id, created_at);
