-- V008 — serving read model for the business console (Phase B2)
-- Small, pre-aggregated tables written by quickcart.business.snapshot and read by
-- /api/v1/b/*. Percent metrics are stored as 0..1 fractions; money as NUMERIC.
-- Days and hours are UTC. Every write is an upsert keyed by (scope, metric, period),
-- so re-running a snapshot is idempotent.

CREATE SCHEMA IF NOT EXISTS serving;

CREATE TABLE IF NOT EXISTS serving.snapshot_runs (
    snapshot_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at     TIMESTAMPTZ,
    status          TEXT NOT NULL DEFAULT 'running'
        CHECK (status IN ('running', 'succeeded', 'failed')),
    source          TEXT NOT NULL DEFAULT 'postgres'
        CHECK (source IN ('gold', 'postgres')),
    as_of_day       DATE,
    window_days     INTEGER NOT NULL DEFAULT 14 CHECK (window_days > 0),
    rows_written    INTEGER NOT NULL DEFAULT 0 CHECK (rows_written >= 0),
    error           TEXT,
    detail          JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_snapshot_runs_finished
    ON serving.snapshot_runs (finished_at DESC) WHERE status = 'succeeded';

CREATE TABLE IF NOT EXISTS serving.metric_daily (
    scope_type      TEXT NOT NULL CHECK (scope_type IN ('global', 'store', 'category')),
    scope_value     TEXT NOT NULL,          -- 'all' for global, store_id / category otherwise
    metric_key      TEXT NOT NULL,          -- key in semantics/metrics.yaml
    day             DATE NOT NULL,
    value           NUMERIC(18, 4),         -- NULL = not computable (e.g. no deliveries)
    numerator       NUMERIC(18, 4),
    denominator     NUMERIC(18, 4),
    snapshot_run_id BIGINT REFERENCES serving.snapshot_runs (snapshot_run_id),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (scope_type, scope_value, metric_key, day)
);

CREATE INDEX IF NOT EXISTS ix_metric_daily_day ON serving.metric_daily (day);

CREATE TABLE IF NOT EXISTS serving.metric_hourly (
    scope_type      TEXT NOT NULL CHECK (scope_type IN ('global', 'store', 'category')),
    scope_value     TEXT NOT NULL,
    metric_key      TEXT NOT NULL,
    hour_start      TIMESTAMPTZ NOT NULL,
    value           NUMERIC(18, 4),
    snapshot_run_id BIGINT REFERENCES serving.snapshot_runs (snapshot_run_id),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (scope_type, scope_value, metric_key, hour_start)
);

CREATE INDEX IF NOT EXISTS ix_metric_hourly_hour ON serving.metric_hourly (hour_start);

CREATE TABLE IF NOT EXISTS serving.store_scorecard (
    store_id             BIGINT NOT NULL REFERENCES stores (store_id),
    day                  DATE NOT NULL,
    sales                NUMERIC(18, 2),
    orders               INTEGER,
    average_basket       NUMERIC(18, 2),
    on_time_rate         NUMERIC(9, 4),
    late_rate            NUMERIC(9, 4),
    cancel_rate          NUMERIC(9, 4),
    avg_delivery_minutes NUMERIC(9, 2),
    payment_failure_rate NUMERIC(9, 4),
    stockout_risk_count  INTEGER,
    active_customers     INTEGER,
    health_status        TEXT NOT NULL DEFAULT 'unknown'
        CHECK (health_status IN ('good', 'watch', 'bad', 'unknown')),
    snapshot_run_id      BIGINT REFERENCES serving.snapshot_runs (snapshot_run_id),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (store_id, day)
);

CREATE INDEX IF NOT EXISTS ix_store_scorecard_day ON serving.store_scorecard (day);

CREATE TABLE IF NOT EXISTS serving.category_daily (
    category        TEXT NOT NULL,
    day             DATE NOT NULL,
    sales           NUMERIC(18, 2) NOT NULL DEFAULT 0,
    units           BIGINT NOT NULL DEFAULT 0,
    orders          INTEGER NOT NULL DEFAULT 0,
    snapshot_run_id BIGINT REFERENCES serving.snapshot_runs (snapshot_run_id),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (category, day)
);

CREATE INDEX IF NOT EXISTS ix_category_daily_day ON serving.category_daily (day);

COMMENT ON SCHEMA serving IS
    'Business read model: pre-aggregated metrics for /api/v1/b/*, written by quickcart.business.snapshot.';

-- Let the live worker record the serving snapshot as a pipeline stage. The V005 CHECK is
-- inline (auto-named pipeline_status_stage_check); recreate it with the extra stage.
DO $$
BEGIN
    IF to_regclass('public.pipeline_status') IS NOT NULL THEN
        ALTER TABLE pipeline_status DROP CONSTRAINT IF EXISTS pipeline_status_stage_check;
        ALTER TABLE pipeline_status ADD CONSTRAINT pipeline_status_stage_check
            CHECK (stage IN (
                'order_events_bronze',
                'cdc_bronze',
                'cdc_silver',
                'gold_refresh',
                'ml_scoring',
                'anomaly_detect',
                'serving_snapshot',
                'worker'
            ));
    END IF;
END
$$;
