-- V009 — product costs and margin (Phase B6, data wave 1)
-- product_costs holds what QuickCart pays for a product; store_id NULL = chain-wide cost.
-- order_items.unit_cost freezes the cost at order time so margin history never shifts when
-- a cost changes later (NULL = cost unknown; margin reports treat it as "not computable").
-- serving.margin_daily is the pre-aggregated margin waterfall read by /api/v1/b/money.

CREATE TABLE IF NOT EXISTS product_costs (
    product_cost_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL REFERENCES products (product_id),
    store_id        BIGINT REFERENCES stores (store_id),   -- NULL = chain-wide cost
    cost_price      NUMERIC(12, 2) NOT NULL CHECK (cost_price >= 0),
    valid_from      TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to        TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE INDEX IF NOT EXISTS ix_product_costs_lookup
    ON product_costs (product_id, store_id, valid_from DESC);

ALTER TABLE order_items
    ADD COLUMN IF NOT EXISTS unit_cost NUMERIC(12, 2) CHECK (unit_cost IS NULL OR unit_cost >= 0);

CREATE SCHEMA IF NOT EXISTS serving;

-- Margin waterfall per store and day (UTC, by order placed day, non-cancelled orders):
--   gross_sales  = sum(orders.subtotal + item_discount)   list-price value before discounts
--   discounts    = sum(item_discount + promo_discount)
--   net_sales    = gross_sales - discounts
--   cogs         = sum(quantity * unit_cost)              NULL when no line has a known cost
--   refunds      = sum(refunds.amount) paid on those orders
--   contribution_margin = net_sales - cogs - refunds      NULL when cogs is NULL
CREATE TABLE IF NOT EXISTS serving.margin_daily (
    store_id            BIGINT NOT NULL REFERENCES stores (store_id),
    day                 DATE NOT NULL,
    gross_sales         NUMERIC(18, 2) NOT NULL DEFAULT 0,
    discounts           NUMERIC(18, 2) NOT NULL DEFAULT 0,
    net_sales           NUMERIC(18, 2) NOT NULL DEFAULT 0,
    cogs                NUMERIC(18, 2),
    cost_coverage       NUMERIC(9, 4),          -- share of order lines with a known cost, 0..1
    refunds             NUMERIC(18, 2) NOT NULL DEFAULT 0,
    contribution_margin NUMERIC(18, 2),
    margin_pct          NUMERIC(9, 4),          -- contribution_margin / net_sales, 0..1
    orders              INTEGER NOT NULL DEFAULT 0,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (store_id, day)
);

CREATE INDEX IF NOT EXISTS ix_margin_daily_day ON serving.margin_daily (day);
