-- V010 — targets and budgets (Phase B6, data wave 1)
-- targets: what a scope is expected to deliver in a period; read by GET /api/v1/b/targets
-- for MTD-vs-target pacing. Additive metrics (sales_gmv, orders) hold the full-period total;
-- rate metrics (on_time_rate, cancel_rate) hold the level to hold across the period.
-- The simulator seeds targets from the trailing 28-day average x 1.1 (see simulator/business.py);
-- people with `target:write` may overwrite them (set_by records who).
-- budgets: money a scope may spend on something (promo discounts, wastage) in a period.

CREATE TABLE targets (
    target_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     TEXT NOT NULL CHECK (scope_type IN ('global', 'city', 'store', 'category')),
    scope_value    TEXT NOT NULL DEFAULT 'all',      -- 'all' for global, else store_id / city / category
    metric_key     TEXT NOT NULL,                    -- key in semantics/metrics.yaml
    period_type    TEXT NOT NULL CHECK (period_type IN ('day', 'week', 'month')),
    period_start   DATE NOT NULL,                    -- first UTC day of the period
    target_value   NUMERIC(18, 4) NOT NULL CHECK (target_value >= 0),
    set_by         TEXT NOT NULL DEFAULT 'system',
    set_by_user_id BIGINT REFERENCES app_users (user_id) ON DELETE SET NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scope_type, scope_value, metric_key, period_type, period_start)
);

CREATE INDEX ix_targets_period ON targets (period_type, period_start);

CREATE TABLE budgets (
    budget_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     TEXT NOT NULL CHECK (scope_type IN ('global', 'city', 'store', 'category')),
    scope_value    TEXT NOT NULL DEFAULT 'all',
    budget_key     TEXT NOT NULL CHECK (budget_key IN ('promo_discount', 'wastage', 'marketing')),
    period_type    TEXT NOT NULL CHECK (period_type IN ('day', 'week', 'month')),
    period_start   DATE NOT NULL,
    amount         NUMERIC(18, 2) NOT NULL CHECK (amount >= 0),
    set_by         TEXT NOT NULL DEFAULT 'system',
    set_by_user_id BIGINT REFERENCES app_users (user_id) ON DELETE SET NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scope_type, scope_value, budget_key, period_type, period_start)
);

CREATE INDEX ix_budgets_period ON budgets (period_type, period_start);
