-- V011 — refunds, stock batches and wastage (Phase B6, data wave 1)
-- refunds: money returned to a customer for an order (late delivery, damaged item, ...).
--   Separate from payments.status = 'REFUNDED' (which marks a failed-checkout reversal).
-- inventory_batches: received lots with a cost and optional expiry, so wastage can be priced.
-- wastage_events: stock written off (expired / damaged / spoiled). Seeded rows are a ledger of
--   losses only; they do NOT move inventory.on_hand_qty (use inventory_movements DAMAGE for that).

CREATE TABLE refunds (
    refund_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL REFERENCES orders (order_id),
    payment_id  BIGINT REFERENCES payments (payment_id),
    amount      NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    reason      TEXT NOT NULL CHECK (reason IN
        ('LATE_DELIVERY', 'DAMAGED_ITEM', 'MISSING_ITEM', 'QUALITY', 'WRONG_ITEM', 'OTHER')),
    status      TEXT NOT NULL DEFAULT 'PAID' CHECK (status IN ('REQUESTED', 'APPROVED', 'PAID', 'REJECTED')),
    issued_by   TEXT NOT NULL DEFAULT 'system',
    refunded_at TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_refunds_order ON refunds (order_id);
CREATE INDEX ix_refunds_refunded_at ON refunds (refunded_at);

CREATE TABLE inventory_batches (
    batch_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id      BIGINT NOT NULL REFERENCES stores (store_id),
    product_id    BIGINT NOT NULL REFERENCES products (product_id),
    received_qty  INTEGER NOT NULL CHECK (received_qty > 0),
    remaining_qty INTEGER NOT NULL CHECK (remaining_qty >= 0),
    unit_cost     NUMERIC(12, 2) CHECK (unit_cost IS NULL OR unit_cost >= 0),
    received_at   TIMESTAMPTZ NOT NULL,
    expires_at    TIMESTAMPTZ,                     -- NULL = does not expire
    source        TEXT NOT NULL DEFAULT 'SEED',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (remaining_qty <= received_qty),
    CHECK (expires_at IS NULL OR expires_at > received_at)
);

CREATE INDEX ix_inventory_batches_lookup ON inventory_batches (store_id, product_id, received_at);
CREATE INDEX ix_inventory_batches_expiry ON inventory_batches (expires_at) WHERE expires_at IS NOT NULL;

CREATE TABLE wastage_events (
    wastage_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id    BIGINT NOT NULL REFERENCES stores (store_id),
    product_id  BIGINT NOT NULL REFERENCES products (product_id),
    batch_id    BIGINT REFERENCES inventory_batches (batch_id),
    quantity    INTEGER NOT NULL CHECK (quantity > 0),
    reason      TEXT NOT NULL CHECK (reason IN ('EXPIRED', 'DAMAGED', 'SPOILED', 'THEFT', 'OTHER')),
    unit_cost   NUMERIC(12, 2) CHECK (unit_cost IS NULL OR unit_cost >= 0),
    cost_amount NUMERIC(12, 2) CHECK (cost_amount IS NULL OR cost_amount >= 0),   -- quantity * unit_cost
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_wastage_events_store_day ON wastage_events (store_id, occurred_at);
