-- V012 — promotion redemptions and promo budgets (Phase B6, data wave 1)
-- promotion_redemptions: one row per order that used a promotion, with the discount it cost.
--   (orders.promotion_id says *which* promotion; this table is the audit grain Gold reads.)
-- promotions.budget_amount / funded_by: the cap on total discount and who pays for it.
--   Both are appended at the end of the table, so positional readers of promotions keep working.

CREATE TABLE promotion_redemptions (
    redemption_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id    BIGINT NOT NULL REFERENCES promotions (promotion_id),
    order_id        BIGINT NOT NULL REFERENCES orders (order_id),
    customer_id     BIGINT REFERENCES customers (customer_id),
    discount_amount NUMERIC(12, 2) NOT NULL CHECK (discount_amount >= 0),
    redeemed_at     TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (promotion_id, order_id)
);

CREATE INDEX ix_promotion_redemptions_promo ON promotion_redemptions (promotion_id, redeemed_at);
CREATE INDEX ix_promotion_redemptions_order ON promotion_redemptions (order_id);

ALTER TABLE promotions
    ADD COLUMN IF NOT EXISTS budget_amount NUMERIC(12, 2)
        CHECK (budget_amount IS NULL OR budget_amount >= 0);
ALTER TABLE promotions
    ADD COLUMN IF NOT EXISTS funded_by TEXT NOT NULL DEFAULT 'COMPANY'
        CHECK (funded_by IN ('COMPANY', 'BRAND', 'SHARED'));
