-- V013 — customer feedback (Phase B6, data wave 1)
-- order_ratings: 1-5 star rating of one delivered order (at most one per order).
-- nps_responses: 0-10 "would you recommend us" score from a customer; category follows the
--   standard NPS bands (0-6 detractor, 7-8 passive, 9-10 promoter).

CREATE TABLE order_ratings (
    rating_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL UNIQUE REFERENCES orders (order_id),
    customer_id BIGINT NOT NULL REFERENCES customers (customer_id),
    rating      SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     TEXT,
    rated_at    TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_order_ratings_rated_at ON order_ratings (rated_at);

CREATE TABLE nps_responses (
    nps_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT NOT NULL REFERENCES customers (customer_id),
    order_id     BIGINT REFERENCES orders (order_id),
    score        SMALLINT NOT NULL CHECK (score BETWEEN 0 AND 10),
    category     TEXT NOT NULL CHECK (category IN ('DETRACTOR', 'PASSIVE', 'PROMOTER')),
    comment      TEXT,
    responded_at TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (
        (score <= 6 AND category = 'DETRACTOR')
        OR (score BETWEEN 7 AND 8 AND category = 'PASSIVE')
        OR (score >= 9 AND category = 'PROMOTER')
    )
);

CREATE INDEX ix_nps_responses_responded_at ON nps_responses (responded_at);
