-- V014 — alert rules, alerts and notifications (Phase B7, data wave 2)
-- alert_rules: a threshold a person asked to be told about ("on-time below 85% at any store").
-- alerts: things that need attention, raised by rules or by the engine from anomalies and stock
--   risks (quickcart.business.alerts). alert_key de-duplicates: at most one OPEN/ACKNOWLEDGED
--   alert per key, so re-running the engine refreshes an alert instead of duplicating it.
-- notifications: what was sent to whom about an alert (in-app now; email/slack later).

CREATE TABLE alert_rules (
    rule_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               TEXT NOT NULL,
    metric_key         TEXT NOT NULL,
    scope_type         TEXT NOT NULL DEFAULT 'global' CHECK (scope_type IN ('global', 'city', 'store', 'category')),
    scope_value        TEXT NOT NULL DEFAULT 'all',
    comparator         TEXT NOT NULL CHECK (comparator IN ('lt', 'lte', 'gt', 'gte')),
    threshold          NUMERIC(18, 4) NOT NULL,
    severity           TEXT NOT NULL DEFAULT 'watch' CHECK (severity IN ('watch', 'bad')),
    channel            TEXT NOT NULL DEFAULT 'in_app' CHECK (channel IN ('in_app', 'email', 'slack')),
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id BIGINT REFERENCES app_users (user_id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE alerts (
    alert_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id          BIGINT REFERENCES alert_rules (rule_id) ON DELETE SET NULL,
    alert_key        TEXT NOT NULL,
    kind             TEXT NOT NULL CHECK (kind IN
        ('ANOMALY', 'STOCK_RISK', 'METRIC_THRESHOLD', 'TARGET_PACE', 'OTHER')),
    severity         TEXT NOT NULL CHECK (severity IN ('watch', 'bad')),
    title            TEXT NOT NULL,
    detail           TEXT NOT NULL,
    suggested_action TEXT,
    metric_key       TEXT,
    store_id         BIGINT REFERENCES stores (store_id),
    product_id       BIGINT REFERENCES products (product_id),
    evidence         JSONB NOT NULL DEFAULT '{}'::jsonb,
    status           TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')),
    first_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    acknowledged_at  TIMESTAMPTZ,
    resolved_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_alerts_active_key ON alerts (alert_key) WHERE status IN ('OPEN', 'ACKNOWLEDGED');
CREATE INDEX ix_alerts_status_seen ON alerts (status, last_seen_at DESC);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT REFERENCES app_users (user_id) ON DELETE CASCADE,   -- NULL = everyone
    alert_id        BIGINT REFERENCES alerts (alert_id) ON DELETE CASCADE,
    channel         TEXT NOT NULL DEFAULT 'in_app' CHECK (channel IN ('in_app', 'email', 'slack')),
    title           TEXT NOT NULL,
    body            TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SENT', 'READ', 'FAILED')),
    sent_at         TIMESTAMPTZ,
    read_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_notifications_user ON notifications (user_id, status, created_at DESC);
