-- V015 — suppliers and procurement (Phase B7, data wave 2)
-- suppliers -> supplier_products (what each supplier sells and at what cost)
-- purchase_orders -> purchase_order_lines (what we asked for)
-- goods_receipts -> goods_receipt_lines (what actually arrived, against a PO line)
-- A purchase order may point back to the approved proposal that created it (PO_CREATE).
-- Tables only: nothing seeds or executes procurement yet (the PO_CREATE executor is a stub).

CREATE TABLE suppliers (
    supplier_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code  TEXT NOT NULL UNIQUE,
    name           TEXT NOT NULL,
    contact_email  TEXT,
    lead_time_days INTEGER NOT NULL DEFAULT 2 CHECK (lead_time_days >= 0),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE supplier_products (
    supplier_product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         BIGINT NOT NULL REFERENCES suppliers (supplier_id),
    product_id          BIGINT NOT NULL REFERENCES products (product_id),
    cost_price          NUMERIC(12, 2) NOT NULL CHECK (cost_price >= 0),
    min_order_qty       INTEGER NOT NULL DEFAULT 1 CHECK (min_order_qty > 0),
    lead_time_days      INTEGER CHECK (lead_time_days IS NULL OR lead_time_days >= 0),
    is_preferred        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (supplier_id, product_id)
);

CREATE INDEX ix_supplier_products_product ON supplier_products (product_id);

CREATE TABLE purchase_orders (
    po_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id          BIGINT NOT NULL REFERENCES suppliers (supplier_id),
    store_id             BIGINT NOT NULL REFERENCES stores (store_id),
    status               TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN
        ('DRAFT', 'SUBMITTED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')),
    proposal_id          BIGINT REFERENCES proposals (proposal_id),
    created_by_user_id   BIGINT REFERENCES app_users (user_id) ON DELETE SET NULL,
    total_amount         NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    ordered_at           TIMESTAMPTZ,
    expected_delivery_at TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_purchase_orders_status ON purchase_orders (status, store_id);

CREATE TABLE purchase_order_lines (
    po_line_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id            BIGINT NOT NULL REFERENCES purchase_orders (po_id) ON DELETE CASCADE,
    product_id       BIGINT NOT NULL REFERENCES products (product_id),
    quantity_ordered INTEGER NOT NULL CHECK (quantity_ordered > 0),
    unit_cost        NUMERIC(12, 2) NOT NULL CHECK (unit_cost >= 0),
    UNIQUE (po_id, product_id)
);

CREATE TABLE goods_receipts (
    grn_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id             BIGINT NOT NULL REFERENCES purchase_orders (po_id),
    received_by       TEXT NOT NULL DEFAULT 'system',
    received_at       TIMESTAMPTZ NOT NULL,
    notes             TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_goods_receipts_po ON goods_receipts (po_id);

CREATE TABLE goods_receipt_lines (
    grn_line_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grn_id            BIGINT NOT NULL REFERENCES goods_receipts (grn_id) ON DELETE CASCADE,
    po_line_id        BIGINT NOT NULL REFERENCES purchase_order_lines (po_line_id),
    quantity_received INTEGER NOT NULL CHECK (quantity_received >= 0),
    quantity_rejected INTEGER NOT NULL DEFAULT 0 CHECK (quantity_rejected >= 0),
    unit_cost         NUMERIC(12, 2) CHECK (unit_cost IS NULL OR unit_cost >= 0)
);
