-- V016 — rider shifts (Phase B7, data wave 2)
-- One row per rider per day: the planned window, the actual window, and whether they showed up.
-- riders.shift_start/shift_end stay the static template; this table is the attendance record
-- (planned vs actual, no-shows) that rider-productivity marts read. Table only: nothing seeds it yet.

CREATE TABLE rider_shifts (
    shift_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id           BIGINT NOT NULL REFERENCES riders (rider_id),
    store_id           BIGINT NOT NULL REFERENCES stores (store_id),
    shift_date         DATE NOT NULL,                          -- UTC day the shift starts
    planned_start_at   TIMESTAMPTZ NOT NULL,
    planned_end_at     TIMESTAMPTZ NOT NULL,
    actual_start_at    TIMESTAMPTZ,
    actual_end_at      TIMESTAMPTZ,
    status             TEXT NOT NULL DEFAULT 'PLANNED' CHECK (status IN
        ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'NO_SHOW', 'CANCELLED')),
    orders_delivered   INTEGER NOT NULL DEFAULT 0 CHECK (orders_delivered >= 0),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (rider_id, shift_date),
    CHECK (planned_end_at > planned_start_at),
    CHECK (actual_end_at IS NULL OR actual_start_at IS NULL OR actual_end_at >= actual_start_at)
);

CREATE INDEX ix_rider_shifts_store_date ON rider_shifts (store_id, shift_date);
