-- V017 — assistant history, saved reports, and proposals v2 (Phase B7, data wave 2)
-- assistant_sessions / assistant_messages: persisted copilot conversations (cards + tool calls).
-- llm_usage: one row per model call, for cost and latency reporting.
-- saved_reports / report_runs: a named report definition and each time it was run.
-- proposals v2: widen proposal_type, and record who created/approved, through which channel,
--   and how risky the action is. The V004 CHECK is inline (auto-named
--   proposals_proposal_type_check); it is dropped and recreated with the extra types.

CREATE TABLE assistant_sessions (
    session_id  UUID PRIMARY KEY,
    user_id     BIGINT REFERENCES app_users (user_id) ON DELETE SET NULL,
    title       TEXT,
    context     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_assistant_sessions_user ON assistant_sessions (user_id, updated_at DESC);

CREATE TABLE assistant_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES assistant_sessions (session_id) ON DELETE CASCADE,
    role       TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'tool', 'system')),
    content    TEXT NOT NULL,
    cards      JSONB NOT NULL DEFAULT '[]'::jsonb,
    tool_calls JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_assistant_messages_session ON assistant_messages (session_id, message_id);

CREATE TABLE llm_usage (
    usage_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        UUID REFERENCES assistant_sessions (session_id) ON DELETE SET NULL,
    user_id           BIGINT REFERENCES app_users (user_id) ON DELETE SET NULL,
    request_id        TEXT,
    provider          TEXT,
    model             TEXT NOT NULL,
    prompt_tokens     INTEGER NOT NULL DEFAULT 0 CHECK (prompt_tokens >= 0),
    completion_tokens INTEGER NOT NULL DEFAULT 0 CHECK (completion_tokens >= 0),
    latency_ms        INTEGER CHECK (latency_ms IS NULL OR latency_ms >= 0),
    cost_usd          NUMERIC(12, 6) CHECK (cost_usd IS NULL OR cost_usd >= 0),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_llm_usage_created ON llm_usage (created_at);

CREATE TABLE saved_reports (
    report_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    description   TEXT,
    owner_user_id BIGINT REFERENCES app_users (user_id) ON DELETE SET NULL,
    definition    JSONB NOT NULL DEFAULT '{}'::jsonb,     -- metric keys, scope, period, layout
    schedule_cron TEXT,                                    -- NULL = on demand only
    is_shared     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_saved_reports_owner ON saved_reports (owner_user_id, created_at DESC);

CREATE TABLE report_runs (
    run_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id    BIGINT NOT NULL REFERENCES saved_reports (report_id) ON DELETE CASCADE,
    status       TEXT NOT NULL DEFAULT 'QUEUED' CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    triggered_by TEXT NOT NULL DEFAULT 'manual',
    row_count    INTEGER CHECK (row_count IS NULL OR row_count >= 0),
    result       JSONB,
    error        TEXT,
    started_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at  TIMESTAMPTZ
);

CREATE INDEX ix_report_runs_report ON report_runs (report_id, started_at DESC);

-- Proposals v2 ---------------------------------------------------------------------------------

ALTER TABLE proposals DROP CONSTRAINT IF EXISTS proposals_proposal_type_check;
ALTER TABLE proposals ADD CONSTRAINT proposals_proposal_type_check
    CHECK (proposal_type IN (
        'RESTOCK', 'INCIDENT', 'OPS_NOTIFICATION',
        'PROMO_PAUSE', 'PROMO_LAUNCH', 'TARGET_CHANGE', 'STORE_NOTIFY', 'TRANSFER', 'PO_CREATE'
    ));

ALTER TABLE proposals
    ADD COLUMN IF NOT EXISTS created_by_user_id BIGINT REFERENCES app_users (user_id) ON DELETE SET NULL;
ALTER TABLE proposals
    ADD COLUMN IF NOT EXISTS approved_by_user_id BIGINT REFERENCES app_users (user_id) ON DELETE SET NULL;
ALTER TABLE proposals
    ADD COLUMN IF NOT EXISTS channel TEXT NOT NULL DEFAULT 'web'
        CHECK (channel IN ('web', 'agent', 'voice', 'system'));
ALTER TABLE proposals
    ADD COLUMN IF NOT EXISTS risk_level TEXT NOT NULL DEFAULT 'low'
        CHECK (risk_level IN ('low', 'medium', 'high'));
