"""Bulk-load helpers: COPY-based inserts for simulator output.

Domain code (simulator) produces plain row tuples; this adapter owns the
database I/O so generation stays pure and testable without a database.
"""

from collections.abc import Iterable, Sequence
from typing import Any

import psycopg
from psycopg.sql import SQL, Identifier, Literal

ALL_TABLES = [
    "support_tickets",
    "deliveries",
    "payments",
    "order_items",
    "orders",
    "inventory_movements",
    "inventory",
    "promotions",
    "riders",
    "product_prices",
    "products",
    "customer_addresses",
    "customers",
    "stores",
]


def copy_rows(
    cur: psycopg.Cursor,
    table: str,
    columns: Sequence[str],
    rows: Iterable[Sequence[Any]],
) -> int:
    """COPY rows into `table` in one round trip. Returns rows written."""
    column_list = ", ".join(columns)
    count = 0
    with cur.copy(f"COPY {table} ({column_list}) FROM STDIN") as copy:
        for row in rows:
            copy.write_row(row)
            count += 1
    return count


def truncate_all(cur: psycopg.Cursor) -> None:
    """Reset every business table (RESTART IDENTITY + CASCADE). Destructive."""
    cur.execute(f"TRUNCATE TABLE {', '.join(ALL_TABLES)} RESTART IDENTITY CASCADE")


def sync_identity_sequences(cur: psycopg.Cursor, tables: Sequence[str]) -> None:
    """Re-sync identity sequences after COPY of explicit id values.

    `GENERATED BY DEFAULT AS IDENTITY` columns accept explicit inserts (the
    deterministic seed relies on that) but the sequence does not advance, so
    the first later insert without an explicit id would collide with an
    existing key. Set every identity sequence backing `tables` to
    max(id) + 1 (not called), making subsequent generated inserts safe.
    """
    cur.execute(
        """
        SELECT c.table_name, c.column_name
        FROM information_schema.columns c
        WHERE c.table_schema = 'public'
          AND c.is_identity = 'YES'
          AND c.table_name = ANY(%s)
        ORDER BY c.table_name, c.column_name
        """,
        (list(tables),),
    )
    for table, column in cur.fetchall():
        cur.execute(
            SQL(
                "SELECT setval(pg_get_serial_sequence({seq_t}, {seq_c}),"
                " COALESCE((SELECT MAX({pk}) FROM {tbl}), 0) + 1, false)"
            ).format(
                seq_t=Literal(table),
                seq_c=Literal(column),
                pk=Identifier(column),
                tbl=Identifier(table),
            )
        )
