"""Persist generated data into PostgreSQL (adapter layer).

Column orders match `infrastructure/postgres/migrations/V001__core_schema.sql`
exactly. All IDs come from the generator (GENERATED BY DEFAULT identities),
so reruns are deterministic.
"""

import psycopg

from quickcart.db.fingerprints import canonical_row_fingerprint
from quickcart.db.loader import ALL_TABLES, copy_rows, sync_identity_sequences, truncate_all
from quickcart.simulator.generator import ReferenceData

STORE_COLUMNS = (
    "store_id", "store_code", "name", "city", "latitude", "longitude",
    "service_radius_km", "opened_at", "is_active", "created_at", "updated_at",
)
CUSTOMER_COLUMNS = ("customer_id", "customer_code", "created_at", "updated_at", "is_active")
ADDRESS_COLUMNS = (
    "address_id", "customer_id", "city", "postal_code", "latitude", "longitude",
    "is_default", "valid_from", "valid_to", "created_at", "updated_at",
)
PRODUCT_COLUMNS = (
    "product_id", "sku", "name", "category", "subcategory", "brand",
    "unit_size", "unit_name", "is_active", "created_at", "updated_at",
)
PRICE_COLUMNS = (
    "product_price_id", "product_id", "store_id", "mrp", "selling_price",
    "valid_from", "valid_to", "created_at",
)
RIDER_COLUMNS = (
    "rider_id", "home_store_id", "status", "shift_start", "shift_end",
    "created_at", "updated_at",
)
PROMOTION_COLUMNS = (
    "promotion_id", "name", "promotion_type", "value", "starts_at", "ends_at",
    "min_order_value", "max_discount", "is_active",
)
ORDER_COLUMNS = (
    "order_id", "customer_id", "store_id", "address_id", "promotion_id", "status",
    "subtotal", "item_discount", "promo_discount", "delivery_fee", "tax_amount",
    "total_amount", "currency", "placed_at", "updated_at",
)
ORDER_ITEM_COLUMNS = (
    "order_item_id", "order_id", "product_id", "quantity", "unit_price",
    "line_discount", "line_total", "created_at",
)
PAYMENT_COLUMNS = (
    "payment_id", "order_id", "payment_method", "status", "amount", "currency",
    "attempt_number", "failure_code", "created_at", "updated_at",
)
DELIVERY_COLUMNS = (
    "delivery_id", "order_id", "rider_id", "promised_by", "assigned_at",
    "picked_up_at", "delivered_at", "cancelled_at", "estimated_distance_km",
    "status", "created_at", "updated_at",
)
MOVEMENT_COLUMNS = (
    "movement_id", "store_id", "product_id", "movement_type", "quantity_delta",
    "reference_type", "reference_id", "occurred_at", "created_at",
)
TICKET_COLUMNS = (
    "ticket_id", "customer_id", "order_id", "category", "priority", "status",
    "subject", "body", "created_at", "updated_at",
)
INVENTORY_COLUMNS = (
    "store_id", "product_id", "on_hand_qty", "reserved_qty", "reorder_point",
    "updated_at",
)

TRANSACTIONAL_TABLES = [
    "support_tickets",
    "deliveries",
    "payments",
    "order_items",
    "orders",
    "inventory_movements",
    "inventory",
]


def load_reference(cur: psycopg.Cursor, ref: ReferenceData) -> None:
    copy_rows(cur, "stores", STORE_COLUMNS, ref.stores)
    copy_rows(cur, "customers", CUSTOMER_COLUMNS, ref.customers)
    copy_rows(cur, "customer_addresses", ADDRESS_COLUMNS, ref.addresses)
    copy_rows(cur, "products", PRODUCT_COLUMNS, ref.products)
    copy_rows(cur, "product_prices", PRICE_COLUMNS, ref.prices)
    copy_rows(cur, "riders", RIDER_COLUMNS, ref.riders)
    copy_rows(cur, "promotions", PROMOTION_COLUMNS, ref.promotions)
    sync_identity_sequences(cur, ALL_TABLES)


def truncate_transactional(cur: psycopg.Cursor) -> None:
    cur.execute(f"TRUNCATE TABLE {', '.join(TRANSACTIONAL_TABLES)} RESTART IDENTITY CASCADE")


def load_history(cur: psycopg.Cursor, history) -> None:
    """Load order-era rows plus the end-of-history inventory snapshot."""
    truncate_transactional(cur)
    copy_rows(cur, "orders", ORDER_COLUMNS, history.orders)
    copy_rows(cur, "order_items", ORDER_ITEM_COLUMNS, history.order_items)
    copy_rows(cur, "payments", PAYMENT_COLUMNS, history.payments)
    copy_rows(cur, "deliveries", DELIVERY_COLUMNS, history.deliveries)
    copy_rows(cur, "inventory_movements", MOVEMENT_COLUMNS, history.movements)
    copy_rows(cur, "support_tickets", TICKET_COLUMNS, history.tickets)
    copy_rows(cur, "inventory", INVENTORY_COLUMNS, history.inventory)
    sync_identity_sequences(cur, TRANSACTIONAL_TABLES)


def db_reference_fingerprint(conn: psycopg.Connection) -> str:
    """Fingerprint of the reference data currently in the database."""
    tables = (
        "stores", "customers", "customer_addresses",
        "products", "product_prices", "riders", "promotions",
    )
    row_sets: list[tuple[str, list[tuple]]] = []
    for table in tables:
        with conn.cursor() as cur:
            cur.execute(f"SELECT * FROM {table} ORDER BY 1")
            row_sets.append((table, cur.fetchall()))
    return canonical_row_fingerprint(row_sets)


def truncate_all_tables(cur: psycopg.Cursor) -> None:
    truncate_all(cur)
